# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements/testing.txt
    sudo apt install -y gfortran
    pip install -e .
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines codecov pytest-cov
    pytest --cov=streamtracer
    codecov --token=4847529e-2a8f-4bf0-912f-ec8f5f98b3f8
  displayName: 'pytest'
